/*
 * Arm SCP/MCP Software
 * Copyright (c) 2026, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef ARCH_EXCEPTIONS_H
#define ARCH_EXCEPTIONS_H

#ifndef __ASSEMBLER__
#    include <stdint.h>
#endif

#define AARCH64_EXCEPTION_VECTOR_IDX_SYNC_CURRENT_EL_SP0     0
#define AARCH64_EXCEPTION_VECTOR_IDX_IRQ_CURRENT_EL_SP0      1
#define AARCH64_EXCEPTION_VECTOR_IDX_FIQ_CURRENT_EL_SP0      2
#define AARCH64_EXCEPTION_VECTOR_IDX_SERROR_CURRENT_EL_SP0   3
#define AARCH64_EXCEPTION_VECTOR_IDX_SYNC_CURRENT_EL_SPX     4
#define AARCH64_EXCEPTION_VECTOR_IDX_IRQ_CURRENT_EL_SPX      5
#define AARCH64_EXCEPTION_VECTOR_IDX_FIQ_CURRENT_EL_SPX      6
#define AARCH64_EXCEPTION_VECTOR_IDX_SERROR_CURRENT_EL_SPX   7
#define AARCH64_EXCEPTION_VECTOR_IDX_SYNC_LOWER_EL_AARCH64   8
#define AARCH64_EXCEPTION_VECTOR_IDX_IRQ_LOWER_EL_AARCH64    9
#define AARCH64_EXCEPTION_VECTOR_IDX_FIQ_LOWER_EL_AARCH64    10
#define AARCH64_EXCEPTION_VECTOR_IDX_SERROR_LOWER_EL_AARCH64 11
#define AARCH64_EXCEPTION_VECTOR_IDX_SYNC_LOWER_EL_AARCH32   12
#define AARCH64_EXCEPTION_VECTOR_IDX_IRQ_LOWER_EL_AARCH32    13
#define AARCH64_EXCEPTION_VECTOR_IDX_FIQ_LOWER_EL_AARCH32    14
#define AARCH64_EXCEPTION_VECTOR_IDX_SERROR_LOWER_EL_AARCH32 15
#define AARCH64_EXCEPTION_VECTOR_IDX_COUNT                   16

#define AARCH64_EXCEPTION_MAX_BACKTRACE_DEPTH 16
#define AARCH64_EXCEPTION_FRAME_RECORD_SIZE   16
#define AARCH64_EXCEPTION_STACK_ALIGNMENT     16
#define AARCH64_EXCEPTION_STACK_DUMP_SIZE     256

#ifndef AARCH64_EXCEPTION_SYMTAB_MAX_SIZE
#    define AARCH64_EXCEPTION_SYMTAB_MAX_SIZE 0
#endif

#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X0         0x00
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X1         0x08
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X2         0x10
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X3         0x18
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X4         0x20
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X5         0x28
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X6         0x30
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X7         0x38
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X8         0x40
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X9         0x48
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X10        0x50
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X11        0x58
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X12        0x60
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X13        0x68
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X14        0x70
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X15        0x78
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X16        0x80
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X17        0x88
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X18        0x90
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X19        0x98
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X20        0xA0
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X21        0xA8
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X22        0xB0
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X23        0xB8
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X24        0xC0
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X25        0xC8
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X26        0xD0
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X27        0xD8
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X28        0xE0
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X29        0xE8
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_X30        0xF0
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_SP         0xF8
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_SPSR_ELX   0x100
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_ELR_ELX    0x108
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_ESR_ELX    0x110
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_FAR_ELX    0x118
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_VECTOR     0x120
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_MPIDR_EL1  0x128
#define AARCH64_EXCEPTION_CONTEXT_OFFSET_CURRENT_EL 0x130
#define AARCH64_EXCEPTION_CONTEXT_SIZE              0x140

#ifndef __ASSEMBLER__
struct aarch64_symtab_entry {
    uint64_t addr;
    uint32_t name_off;
    uint32_t size;
};

struct aarch64_symtab_blob_header {
    uint32_t magic;
    uint32_t count;
    uint32_t strtab_off;
    uint32_t strtab_size;
};

struct aarch64_symtab {
    uint32_t count;
    const struct aarch64_symtab_entry *entries;
    const char *strtab;
};

extern const struct aarch64_symtab aarch64_symtab;

struct aarch64_exception_context {
    uint64_t x[31];
    uint64_t sp_elx;
    uint64_t spsr_el2;
    uint64_t elr_el2;
    uint64_t esr_el2;
    uint64_t far_el2;
    uint64_t vector;
    uint64_t mpidr_el1;
    uint64_t current_el;
    uint64_t reserved; /* pad to maintain 16-byte stack alignment */
};

void arch_exception_dump(const struct aarch64_exception_context *context);
#endif

#endif /* ARCH_EXCEPTIONS_H */
