/*
 * Arm SCP/MCP Software
 * Copyright (c) 2025-2026, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Description:
 *     Definitions for transport module configuration data in SCP
 *     firmware.
 */

#ifndef SI0_CFGD_TRANSPORT_H
#define SI0_CFGD_TRANSPORT_H

/* Module 'transport' element indexes */
enum scp_cfgd_mod_transport_element_idx {
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_RSE,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PSCI,
#ifdef BUILD_HAS_SCMI_NOTIFICATIONS
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_RSE_P2A, /* SCP to RSE notification */
#endif
#if !RD_ASPEN_VARIANT_CFG1
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_SI_CLUSTER1_CORE_0,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_SI_CLUSTER1_CORE_1,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_SI_CLUSTER1_CORE_2,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_SI_CLUSTER1_CORE_3,
#endif /* RD_ASPEN_VARIANT_CFG1 */
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_0_CORE_0,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_0_CORE_1,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_0_CORE_2,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_0_CORE_3,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_1_CORE_0,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_1_CORE_1,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_1_CORE_2,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_1_CORE_3,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_2_CORE_0,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_2_CORE_1,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_2_CORE_2,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_2_CORE_3,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_3_CORE_0,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_3_CORE_1,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_3_CORE_2,
    SI0_CFGD_MOD_TRANSPORT_EIDX_PFDI_MONITOR_AP_CLUSTER_3_CORE_3,
    SI0_CFGD_MOD_TRANSPORT_IDX_OSPM_A2P,
#ifdef BUILD_HAS_SCMI_NOTIFICATIONS
    SI0_CFGD_MOD_TRANSPORT_IDX_OSPM_P2A,
#endif
#if defined(BUILD_HAS_SCMI_PERF_FAST_CHANNELS)
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER0_LEVEL_SET,
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER0_LIMIT_SET,
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER0_LEVEL_GET,
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER0_LIMIT_GET,

    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER1_LEVEL_SET,
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER1_LIMIT_SET,
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER1_LEVEL_GET,
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER1_LIMIT_GET,

    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER2_LEVEL_SET,
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER2_LIMIT_SET,
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER2_LEVEL_GET,
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER2_LIMIT_GET,

    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER3_LEVEL_SET,
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER3_LIMIT_SET,
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER3_LEVEL_GET,
    SI0_CFGD_MOD_TRANSPORT_EIDX_SCMI_PERF_FCH_CLUSTER3_LIMIT_GET,
#endif
    SI0_CFGD_MOD_TRANSPORT_EIDX_RSE_WARM_SYNC,
    SI0_CFGD_MOD_TRANSPORT_EIDX_COUNT,
};

#endif /* SI0_CFGD_TRANSPORT_H */
