/*
 * Arm SCP/MCP Software
 * Copyright (c) 2025, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Description:
 *     Definitions for timer module configuration data in SCP firmware.
 */

#ifndef SI0_CFGD_TIMER_H
#define SI0_CFGD_TIMER_H

#define SI0_REFCLK_ALARM_ELEMENT_IDX    0
#define SI0_SI0_TIMER_ALARM_ELEMENT_IDX 1

/* Sub-element indexes (alarms) REFCLK device */
enum si0_cfgd_mod_timer_refclk_alarm_idx {
#ifdef BUILD_HAS_SCMI_NOTIFICATIONS
    SI0_CFGD_SCMI_NOTIFICATION_ALARM_IDX,
#endif
    SI0_CFGD_MOD_TIMER_REFCLK_ALARM_IDX_COUNT,
};

/* Sub-element indexes (alarms) for SI0 timer device */
enum si0_cfgd_mod_timer_si0_timer_alarm_idx {
    SI0_CFGD_DEBUGGER_CLI_IDX,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER0_CORE0,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER0_CORE1,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER0_CORE2,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER0_CORE3,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER1_CORE0,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER1_CORE1,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER1_CORE2,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER1_CORE3,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER2_CORE0,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER2_CORE1,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER2_CORE2,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER2_CORE3,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER3_CORE0,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER3_CORE1,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER3_CORE2,
    SI0_CFGD_PFDI_MONITOR_ALARM_IDX_AP_CLUSTER3_CORE3,
    SI0_CFGD_MOD_TIMER_SI0_TIMER_ALARM_IDX_COUNT,
};

#endif /* SI0_CFGD_TIMER_H */
