/*
 * Arm SCP/MCP Software
 * Copyright (c) 2025, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Description:
 *     Safety Island Cluster PFDI Monitor definitions.
 */

#ifndef SI0_CFGD_PFDI_MONITOR_H
#define SI0_CFGD_PFDI_MONITOR_H

enum si0_cfgd_mod_pfdi_monitor_element_idx {
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_0_CORE_0,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_0_CORE_1,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_0_CORE_2,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_0_CORE_3,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_1_CORE_0,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_1_CORE_1,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_1_CORE_2,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_1_CORE_3,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_2_CORE_0,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_2_CORE_1,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_2_CORE_2,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_2_CORE_3,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_3_CORE_0,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_3_CORE_1,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_3_CORE_2,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_AP_CLUSTER_3_CORE_3,
    SI0_CFGD_MOD_PFDI_MONITOR_EIDX_COUNT,
};

#endif /* SI0_CFGD_PFDI_MONITOR_H */
