/*
 * Arm SCP/MCP Software
 * Copyright (c) 2025-2026, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Description:
 *     Definitions for SCMI module configuration data in SCP firmware.
 */

#ifndef SI0_CFGD_SCMI_H
#define SI0_CFGD_SCMI_H

#define APOLLO_FVP_FCH_RATE 40000

/* SCMI agent identifier indexes in the SCMI agent table */
enum si0_scmi_agent_idx {
    /* 0 is reserved for the platform */
    SI0_SCMI_AGENT_IDX_RSE = 1,
    SI0_SCMI_AGENT_IDX_PSCI = 2,
    SI0_SCMI_AGENT_IDX_PFDI_MONITOR = 3,
    SI0_SCMI_AGENT_IDX_OSPM = 4,
    SI0_SCMI_AGENT_IDX_COUNT,
};

/* AP-facing SCMI agents (reset on AP warm reboot)
 * NOTE: Any new AP-related SCMI agent must be added to this list for warm
 * reset to work correctly.
 */
static const enum si0_scmi_agent_idx si0_ap_facing_scmi_agents[] = {
    SI0_SCMI_AGENT_IDX_PSCI,
    SI0_SCMI_AGENT_IDX_PFDI_MONITOR,
    SI0_SCMI_AGENT_IDX_OSPM,
};

#define SI0_AP_FACING_SCMI_AGENT_COUNT \
    (sizeof(si0_ap_facing_scmi_agents) / sizeof(si0_ap_facing_scmi_agents[0]))

/* Module 'scmi' element indexes (SCMI services supported) */
enum si0_cfgd_mod_scmi_element_idx {
    SI0_CFGD_MOD_SCMI_EIDX_RSE,
    SI0_CFGD_MOD_SCMI_EIDX_PSCI,
#ifdef BUILD_HAS_SCMI_NOTIFICATIONS
    SI0_CFGD_MOD_SCMI_EIDX_RSE_P2A, /* SCP to RSE notification */
#endif
#if (PLATFORM_VARIANT == APOLLO_FVP_VARIANT_FVP) && (!APOLLO_FVP_VARIANT_CFG1)
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_SI_CLUSTER1_CORE_0,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_SI_CLUSTER1_CORE_1,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_SI_CLUSTER1_CORE_2,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_SI_CLUSTER1_CORE_3,
#endif /* APOLLO_FVP_VARIANT_CFG1 */
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_0_CORE_0,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_0_CORE_1,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_0_CORE_2,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_0_CORE_3,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_1_CORE_0,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_1_CORE_1,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_1_CORE_2,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_1_CORE_3,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_2_CORE_0,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_2_CORE_1,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_2_CORE_2,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_2_CORE_3,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_3_CORE_0,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_3_CORE_1,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_3_CORE_2,
    SI0_CFGD_MOD_SCMI_EIDX_PFDI_MONITOR_AP_CLUSTER_3_CORE_3,
    SI0_CFGD_MOD_SCMI_IDX_OSPM_A2P,
#ifdef BUILD_HAS_SCMI_NOTIFICATIONS
    SI0_CFGD_MOD_SCMI_IDX_OSPM_P2A,
#endif
    SI0_CFGD_MOD_SCMI_EIDX_COUNT,
};

/* SCP<->AP Fast channels indexes */
enum apollo_fvp_plat_fch_idx {
    APOLLO_FVP_PLAT_FCH_CLUSTER0_PERF_LEVEL_SET,
    APOLLO_FVP_PLAT_FCH_CLUSTER0_PERF_LIMIT_SET,
    APOLLO_FVP_PLAT_FCH_CLUSTER0_PERF_LEVEL_GET,
    APOLLO_FVP_PLAT_FCH_CLUSTER0_PERF_LIMIT_GET,

    APOLLO_FVP_PLAT_FCH_CLUSTER1_PERF_LEVEL_SET,
    APOLLO_FVP_PLAT_FCH_CLUSTER1_PERF_LIMIT_SET,
    APOLLO_FVP_PLAT_FCH_CLUSTER1_PERF_LEVEL_GET,
    APOLLO_FVP_PLAT_FCH_CLUSTER1_PERF_LIMIT_GET,

    APOLLO_FVP_PLAT_FCH_CLUSTER2_PERF_LEVEL_SET,
    APOLLO_FVP_PLAT_FCH_CLUSTER2_PERF_LIMIT_SET,
    APOLLO_FVP_PLAT_FCH_CLUSTER2_PERF_LEVEL_GET,
    APOLLO_FVP_PLAT_FCH_CLUSTER2_PERF_LIMIT_GET,

    APOLLO_FVP_PLAT_FCH_CLUSTER3_PERF_LEVEL_SET,
    APOLLO_FVP_PLAT_FCH_CLUSTER3_PERF_LIMIT_SET,
    APOLLO_FVP_PLAT_FCH_CLUSTER3_PERF_LEVEL_GET,
    APOLLO_FVP_PLAT_FCH_CLUSTER3_PERF_LIMIT_GET,

    APOLLO_FVP_PLAT_FCH_COUNT,
};
#endif /* SI0_CFGD_SCMI_H */
