/*
 * Arm SCP/MCP Software
 * Copyright (c) 2025, Arm Limited and Contributors. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Description:
 *    SBISTC module configuration (multi-signal, per-fault FMU device/node).
 */

#include <mod_sbistc.h>

#include <fwk_module.h>

#include <stddef.h>

/* FMU device ID for SBISTC Faults */
#define SBISTC_FAULTS_FMU_DEVICE_ID 1

/* Defines for criticality */
#define SBISTC_CR_FLT  true
#define SBISTC_NCR_FLT false

/* Fault IDs for SBISTC faults (platform-specific) */
enum {
    FLT_SBISTC_EQ_FAIL_CORE0,
    FLT_SBISTC_DEADLCK_CORE0,
    FLT_SBISTC_EQ_FAIL_CORE1,
    FLT_SBISTC_DEADLCK_CORE1,
    FLT_SBISTC_EQ_FAIL_CORE2,
    FLT_SBISTC_DEADLCK_CORE2,
    FLT_SBISTC_EQ_FAIL_CORE3,
    FLT_SBISTC_DEADLCK_CORE3,
    FLT_SBISTC_EQ_FAIL_CORE4,
    FLT_SBISTC_DEADLCK_CORE4,
    FLT_SBISTC_EQ_FAIL_CORE5,
    FLT_SBISTC_DEADLCK_CORE5,
    FLT_SBISTC_EQ_FAIL_CORE6,
    FLT_SBISTC_DEADLCK_CORE6,
    FLT_SBISTC_EQ_FAIL_CORE7,
    FLT_SBISTC_DEADLCK_CORE7,
    FLT_SBISTC_EQ_FAIL_CORE8,
    FLT_SBISTC_DEADLCK_CORE8,
    FLT_SBISTC_EQ_FAIL_CORE9,
    FLT_SBISTC_DEADLCK_CORE9,
    FLT_SBISTC_EQ_FAIL_CORE10,
    FLT_SBISTC_DEADLCK_CORE10,
    FLT_SBISTC_EQ_FAIL_CORE11,
    FLT_SBISTC_DEADLCK_CORE11,
    FLT_SBISTC_EQ_FAIL_CORE12,
    FLT_SBISTC_DEADLCK_CORE12,
    FLT_SBISTC_EQ_FAIL_CORE13,
    FLT_SBISTC_DEADLCK_CORE13,
    FLT_SBISTC_EQ_FAIL_CORE14,
    FLT_SBISTC_DEADLCK_CORE14,
    FLT_SBISTC_EQ_FAIL_CORE15,
    FLT_SBISTC_DEADLCK_CORE15,
    FLT_SBISTC_CNT
};

/* SBISTC EQ Failure FMU node ids */
enum {
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE0 = 210,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE1,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE2,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE3,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE4,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE5,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE6,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE7,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE8,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE9,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE10,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE11,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE12,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE13,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE14,
    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE15
};

/* SBISTC Deadlock Failure FMU node ids */
enum {
    FMU_NODE_ID_SBISTC_DEADLCK_CORE0 = 190,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE1,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE2,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE3,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE4,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE5,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE6,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE7,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE8,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE9,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE10,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE11,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE12,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE13,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE14,
    FMU_NODE_ID_SBISTC_DEADLCK_CORE15
};

/* Node ID and device mapping based on your image */
struct sbistc_fault_config sbistc_faults[FLT_SBISTC_CNT + 1] = {
    [FLT_SBISTC_EQ_FAIL_CORE0] = { "SBISTC_EQ_FAIL_CORE0",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_EQ_FAIL_CORE0,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_DEADLCK_CORE0] = { "SBISTC_DEADLCK_CORE0",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_DEADLCK_CORE0,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_EQ_FAIL_CORE1] = { "SBISTC_EQ_FAIL_CORE1",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_EQ_FAIL_CORE1,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_DEADLCK_CORE1] = { "SBISTC_DEADLCK_CORE1",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_DEADLCK_CORE1,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_EQ_FAIL_CORE2] = { "SBISTC_EQ_FAIL_CORE2",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_EQ_FAIL_CORE2,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_DEADLCK_CORE2] = { "SBISTC_DEADLCK_CORE2",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_DEADLCK_CORE2,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_EQ_FAIL_CORE3] = { "SBISTC_EQ_FAIL_CORE3",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_EQ_FAIL_CORE3,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_DEADLCK_CORE3] = { "SBISTC_DEADLCK_CORE3",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_DEADLCK_CORE3,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_EQ_FAIL_CORE4] = { "SBISTC_EQ_FAIL_CORE4",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_EQ_FAIL_CORE4,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_DEADLCK_CORE4] = { "SBISTC_DEADLCK_CORE4",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_DEADLCK_CORE4,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_EQ_FAIL_CORE5] = { "SBISTC_EQ_FAIL_CORE5",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_EQ_FAIL_CORE5,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_DEADLCK_CORE5] = { "SBISTC_DEADLCK_CORE5",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_DEADLCK_CORE5,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_EQ_FAIL_CORE6] = { "SBISTC_EQ_FAIL_CORE6",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_EQ_FAIL_CORE6,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_DEADLCK_CORE6] = { "SBISTC_DEADLCK_CORE6",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_DEADLCK_CORE6,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_EQ_FAIL_CORE7] = { "SBISTC_EQ_FAIL_CORE7",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_EQ_FAIL_CORE7,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_DEADLCK_CORE7] = { "SBISTC_DEADLCK_CORE7",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_DEADLCK_CORE7,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_EQ_FAIL_CORE8] = { "SBISTC_EQ_FAIL_CORE8",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_EQ_FAIL_CORE8,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_DEADLCK_CORE8] = { "SBISTC_DEADLCK_CORE8",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_DEADLCK_CORE8,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_EQ_FAIL_CORE9] = { "SBISTC_EQ_FAIL_CORE9",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_EQ_FAIL_CORE9,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_DEADLCK_CORE9] = { "SBISTC_DEADLCK_CORE9",
                                   SBISTC_FAULTS_FMU_DEVICE_ID,
                                   FMU_NODE_ID_SBISTC_DEADLCK_CORE9,
                                   SBISTC_CR_FLT,
                                   NULL },
    [FLT_SBISTC_EQ_FAIL_CORE10] = { "SBISTC_EQ_FAIL_CORE10",
                                    SBISTC_FAULTS_FMU_DEVICE_ID,
                                    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE10,
                                    SBISTC_CR_FLT,
                                    NULL },
    [FLT_SBISTC_DEADLCK_CORE10] = { "SBISTC_DEADLCK_CORE10",
                                    SBISTC_FAULTS_FMU_DEVICE_ID,
                                    FMU_NODE_ID_SBISTC_DEADLCK_CORE10,
                                    SBISTC_CR_FLT,
                                    NULL },
    [FLT_SBISTC_EQ_FAIL_CORE11] = { "SBISTC_EQ_FAIL_CORE11",
                                    SBISTC_FAULTS_FMU_DEVICE_ID,
                                    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE11,
                                    SBISTC_CR_FLT,
                                    NULL },
    [FLT_SBISTC_DEADLCK_CORE11] = { "SBISTC_DEADLCK_CORE11",
                                    SBISTC_FAULTS_FMU_DEVICE_ID,
                                    FMU_NODE_ID_SBISTC_DEADLCK_CORE11,
                                    SBISTC_CR_FLT,
                                    NULL },
    [FLT_SBISTC_EQ_FAIL_CORE12] = { "SBISTC_EQ_FAIL_CORE12",
                                    SBISTC_FAULTS_FMU_DEVICE_ID,
                                    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE12,
                                    SBISTC_CR_FLT,
                                    NULL },
    [FLT_SBISTC_DEADLCK_CORE12] = { "SBISTC_DEADLCK_CORE12",
                                    SBISTC_FAULTS_FMU_DEVICE_ID,
                                    FMU_NODE_ID_SBISTC_DEADLCK_CORE12,
                                    SBISTC_CR_FLT,
                                    NULL },
    [FLT_SBISTC_EQ_FAIL_CORE13] = { "SBISTC_EQ_FAIL_CORE13",
                                    SBISTC_FAULTS_FMU_DEVICE_ID,
                                    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE13,
                                    SBISTC_CR_FLT,
                                    NULL },
    [FLT_SBISTC_DEADLCK_CORE13] = { "SBISTC_DEADLCK_CORE13",
                                    SBISTC_FAULTS_FMU_DEVICE_ID,
                                    FMU_NODE_ID_SBISTC_DEADLCK_CORE13,
                                    SBISTC_CR_FLT,
                                    NULL },
    [FLT_SBISTC_EQ_FAIL_CORE14] = { "SBISTC_EQ_FAIL_CORE14",
                                    SBISTC_FAULTS_FMU_DEVICE_ID,
                                    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE14,
                                    SBISTC_CR_FLT,
                                    NULL },
    [FLT_SBISTC_DEADLCK_CORE14] = { "SBISTC_DEADLCK_CORE14",
                                    SBISTC_FAULTS_FMU_DEVICE_ID,
                                    FMU_NODE_ID_SBISTC_DEADLCK_CORE14,
                                    SBISTC_CR_FLT,
                                    NULL },
    [FLT_SBISTC_EQ_FAIL_CORE15] = { "SBISTC_EQ_FAIL_CORE15",
                                    SBISTC_FAULTS_FMU_DEVICE_ID,
                                    FMU_NODE_ID_SBISTC_EQ_FAIL_CORE15,
                                    SBISTC_CR_FLT,
                                    NULL },
    [FLT_SBISTC_DEADLCK_CORE15] = { "SBISTC_DEADLCK_CORE15",
                                    SBISTC_FAULTS_FMU_DEVICE_ID,
                                    FMU_NODE_ID_SBISTC_DEADLCK_CORE15,
                                    SBISTC_CR_FLT,
                                    NULL },
    [FLT_SBISTC_CNT] = { NULL, 0, 0, SBISTC_NCR_FLT, NULL }
};

/* Module config for SBISTC */
static struct mod_sbistc_config sbistc_mod_config = {
    .count = FLT_SBISTC_CNT,
    .flt_cfgs = sbistc_faults,
};

/* Framework module config */
const struct fwk_module_config config_sbistc = {
    .data = &sbistc_mod_config,
};
