#!/usr/bin/env python3
#
# Arm SCP/MCP Software
# Copyright (c) 2026, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
"""
Generate an AArch64 exception symbol table C file from an ELF.
"""

import argparse
import subprocess
import sys


SYMBOL_TYPES = {"T", "t", "W", "w"}
MAGIC = 0x5343594D  # "SCYM"


def run_nm(nm_path, elf_path):
    cmd = [nm_path, "-n", "--defined-only", "--print-size", elf_path]
    try:
        return subprocess.check_output(cmd, text=True)
    except subprocess.CalledProcessError as exc:
        sys.stderr.write(exc.output)
        raise


def parse_nm_output(output):
    entries = []
    for line in output.splitlines():
        parts = line.strip().split()
        if len(parts) < 3:
            continue

        # With --print-size: addr size type name
        # Without size: addr type name
        if len(parts) >= 4 and len(parts[1]) > 1:
            addr_str, size_str, sym_type = parts[0], parts[1], parts[2]
            name = parts[3]
        else:
            addr_str, sym_type = parts[0], parts[1]
            name = parts[2]
            size_str = "0"

        if sym_type not in SYMBOL_TYPES:
            continue

        try:
            addr = int(addr_str, 16)
            size = int(size_str, 16)
        except ValueError:
            continue

        entries.append((addr, size, name))

    entries.sort(key=lambda x: x[0])
    return entries


def build_strtab(entries):
    offsets = {}
    data = bytearray()
    for _, _, name in entries:
        if name in offsets:
            continue
        offsets[name] = len(data)
        data.extend(name.encode("ascii", errors="backslashreplace"))
        data.append(0)
    return offsets, data


def write_c_file(out_path, entries):
    offsets, strtab = build_strtab(entries)

    with open(out_path, "w", encoding="ascii") as out:
        out.write("/* Auto-generated by tools/gen_exception_symtab.py */\n")
        out.write("#include <arch_exceptions.h>\n")
        out.write("#include <stdint.h>\n\n")

        out.write("static const char symtab_str[] =\n")
        chunk = []
        for b in strtab:
            if b == 0:
                chunk.append("\\0")
            elif b == 34:
                chunk.append("\\\"")
            elif b == 92:
                chunk.append("\\\\")
            elif 32 <= b <= 126:
                chunk.append(chr(b))
            else:
                chunk.append("\\x%02x" % b)
        out.write("    \"" + "".join(chunk) + "\";\n\n")

        out.write(
            "static const struct aarch64_symtab_entry symtab_entries[] = {\n"
        )
        for addr, size, name in entries:
            out.write(
                "    { 0x%016xULL, %u, %u },\n"
                % (addr, offsets[name], size)
            )
        out.write("};\n\n")

        out.write("const struct aarch64_symtab aarch64_symtab = {\n")
        out.write(
            "    .count = sizeof(symtab_entries) / "
            "sizeof(symtab_entries[0]),\n"
        )
        out.write("    .entries = symtab_entries,\n")
        out.write("    .strtab = symtab_str,\n")
        out.write("};\n")


def write_bin_file(out_path, entries, max_size):
    offsets, strtab = build_strtab(entries)
    count = len(entries)

    entries_data = bytearray()
    for addr, size, name in entries:
        entries_data += addr.to_bytes(8, "little")
        entries_data += offsets[name].to_bytes(4, "little")
        entries_data += size.to_bytes(4, "little")

    header = bytearray()
    header += MAGIC.to_bytes(4, "little")
    header += count.to_bytes(4, "little")
    strtab_off = 16 + len(entries_data)
    header += strtab_off.to_bytes(4, "little")
    header += len(strtab).to_bytes(4, "little")

    blob = header + entries_data + strtab
    if max_size is not None and len(blob) > max_size:
        raise ValueError(
            "symtab blob size %d exceeds max size %d" % (len(blob), max_size)
        )

    with open(out_path, "wb") as out:
        out.write(blob)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("elf", help="Path to firmware ELF")
    parser.add_argument("out", help="Output C source path")
    parser.add_argument("--nm", default="nm", help="Path to nm")
    parser.add_argument(
        "--format", choices=["c", "bin"], default=None, help="Output format"
    )
    parser.add_argument(
        "--max-size",
        type=int,
        default=None,
        help="Max output size in bytes (bin only)",
    )
    args = parser.parse_args()

    nm_output = run_nm(args.nm, args.elf)
    entries = parse_nm_output(nm_output)
    if not entries:
        sys.stderr.write("No symbols found in nm output.\n")
        return 1

    out_format = args.format
    if out_format is None:
        if args.out.endswith(".bin"):
            out_format = "bin"
        else:
            out_format = "c"

    if out_format == "bin":
        write_bin_file(args.out, entries, args.max_size)
    else:
        write_c_file(args.out, entries)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
