/* SPDX-License-Identifier: BSD-3-Clause */
#ifndef TEST_MODULE_IDX_H
#define TEST_MODULE_IDX_H
#include <fwk_id.h>
enum fwk_module_idx { FWK_MODULE_IDX_TIMER, FWK_MODULE_IDX_PL011,
    FWK_MODULE_IDX_PFDI_MONITOR, FWK_MODULE_IDX_POWER_DOMAIN,
    FWK_MODULE_IDX_SI0_PLATFORM, FWK_MODULE_IDX_VMCU_SAFETY,
    FWK_MODULE_IDX_PMIC, FWK_MODULE_IDX_TPS6594, FWK_MODULE_IDX_SDS,
    FWK_MODULE_IDX_SCMI, FWK_MODULE_IDX_TRANSPORT, FWK_MODULE_IDX_PPU_V1,
    FWK_MODULE_IDX_APCONTEXT, FWK_MODULE_IDX_SCMI_SYSTEM_POWER,
    FWK_MODULE_IDX_COUNT };
static const fwk_id_t fwk_module_id_pfdi_monitor =
    FWK_ID_MODULE_INIT(FWK_MODULE_IDX_PFDI_MONITOR);
static const fwk_id_t fwk_module_id_power_domain =
    FWK_ID_MODULE_INIT(FWK_MODULE_IDX_POWER_DOMAIN);
#endif
