/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSI0_PLATFORM_H
#define _MOCKSI0_PLATFORM_H

#include "unity.h"
#include "si0_platform.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mocksi0_platform_Init(void);
void Mocksi0_platform_Destroy(void);
void Mocksi0_platform_Verify(void);




#define platform_power_mgmt_bind_IgnoreAndReturn(cmock_retval) platform_power_mgmt_bind_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void platform_power_mgmt_bind_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define platform_power_mgmt_bind_StopIgnore() platform_power_mgmt_bind_CMockStopIgnore()
void platform_power_mgmt_bind_CMockStopIgnore(void);
#define platform_power_mgmt_bind_ExpectAndReturn(cmock_retval) platform_power_mgmt_bind_CMockExpectAndReturn(__LINE__, cmock_retval)
void platform_power_mgmt_bind_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
typedef int (* CMOCK_platform_power_mgmt_bind_CALLBACK)(int cmock_num_calls);
void platform_power_mgmt_bind_AddCallback(CMOCK_platform_power_mgmt_bind_CALLBACK Callback);
void platform_power_mgmt_bind_Stub(CMOCK_platform_power_mgmt_bind_CALLBACK Callback);
#define platform_power_mgmt_bind_StubWithCallback platform_power_mgmt_bind_Stub
#define get_platform_system_power_driver_api_IgnoreAndReturn(cmock_retval) get_platform_system_power_driver_api_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_platform_system_power_driver_api_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const void* cmock_to_return);
#define get_platform_system_power_driver_api_StopIgnore() get_platform_system_power_driver_api_CMockStopIgnore()
void get_platform_system_power_driver_api_CMockStopIgnore(void);
#define get_platform_system_power_driver_api_ExpectAndReturn(cmock_retval) get_platform_system_power_driver_api_CMockExpectAndReturn(__LINE__, cmock_retval)
void get_platform_system_power_driver_api_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const void* cmock_to_return);
typedef const void* (* CMOCK_get_platform_system_power_driver_api_CALLBACK)(int cmock_num_calls);
void get_platform_system_power_driver_api_AddCallback(CMOCK_get_platform_system_power_driver_api_CALLBACK Callback);
void get_platform_system_power_driver_api_Stub(CMOCK_get_platform_system_power_driver_api_CALLBACK Callback);
#define get_platform_system_power_driver_api_StubWithCallback get_platform_system_power_driver_api_Stub
#define get_platform_scmi_power_down_api_IgnoreAndReturn(cmock_retval) get_platform_scmi_power_down_api_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_platform_scmi_power_down_api_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, const void* cmock_to_return);
#define get_platform_scmi_power_down_api_StopIgnore() get_platform_scmi_power_down_api_CMockStopIgnore()
void get_platform_scmi_power_down_api_CMockStopIgnore(void);
#define get_platform_scmi_power_down_api_ExpectAndReturn(cmock_retval) get_platform_scmi_power_down_api_CMockExpectAndReturn(__LINE__, cmock_retval)
void get_platform_scmi_power_down_api_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const void* cmock_to_return);
typedef const void* (* CMOCK_get_platform_scmi_power_down_api_CALLBACK)(int cmock_num_calls);
void get_platform_scmi_power_down_api_AddCallback(CMOCK_get_platform_scmi_power_down_api_CALLBACK Callback);
void get_platform_scmi_power_down_api_Stub(CMOCK_get_platform_scmi_power_down_api_CALLBACK Callback);
#define get_platform_scmi_power_down_api_StubWithCallback get_platform_scmi_power_down_api_Stub

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
